;;; https://projecteuler.net/problem=2
;;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;;;   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(defn next-fib
  "Returns a vector with [b (a + b)] where the first element is the next fibonacci number."
  [[a b]] 
  [b (+ a b)])

(println
  (reduce +
          (filter even? 
                  (map first
                       (take-while
                         #(< (first %) 4000000)
                         (iterate next-fib [1 1]))))))
